### ISSUE TITLE
Not able to set black as default color in color chooser component

### ISSUE THREAD

**Issue by nidin** [lo-th/uil#1]
**What?**
Not able to set black as default color in color chooser component.
**Why?**
when setting zero as default color following condition is false that result to white as default color.

<pre>
this.value = '#ffffff';
if( o.value ){
	if(o.value instanceof Array) this.value = UIL.pack(o.value);
	else if(!isNaN(o.value)) this.value = UIL.numFormat(o.value);
	else this.value = o.value;
}
</pre>

**Comment by lo-th** [comment]
yes you right is fixed 
if( o.value !== undefined ){...
