### ISSUE TITLE
slight readme.md typo to make things work

### ISSUE THREAD

**Issue by skaparelos** [lo-th/uil#11]
If you copy-paste the code in step2 in the readme.md it crashes because in this line item1, item2 are undefined.
`ui.add('list', { name:'List', callback:callback, list:[item1, item2, ...]});`
quick fix: (notice the quotes in item1, item2, etc..)
`ui.add('list', { name:'List', callback:callback, list:['item1', 'item2', '...']});`

good job with uil

**Comment by lo-th** [comment]
yep thank's
