### ISSUE TITLE
mousedown event not fired when button used for opening a link

### ISSUE THREAD

**Issue by takashi-tk** [lo-th/uil#17]
With the following code is used :
``` javascript
ui.add('button', { name: 'Test', fontColor: '#D4B87B', h: 30 } )
  .onChange( ( ) => { let w = window.open('', ''); } );
```
the mousedown event is not triggered after the execution of the callback.
It seems to be caused by the change of focus on the new tab. I didn't managed to find a solution to avoid this.

**Comment by lo-th** [comment]
Hi, yes i will look that 
all event is call from root and dispatch to proto

**Comment by lo-th** [comment]
mm window.open work ??

**Comment by takashi-tk** [comment]
Yes the window.open code work _(under Chrome at least)_.
At execution, a new tab is opened and this tab is displayed automatically _(standard behavior of browsers - I think it's not possible to change it programmaticaly)_.
At return to the initial page (the one with UIL), the clicked button is still at its "down state" _(visually)_ and the entire page react as a clickable zone _(finger cursor)_. If I click anywhere, the callback of the button is called.

**Comment by lo-th** [comment]
ok i will see what i can do

**Comment by lo-th** [comment]
ok so first solution is open in new window and not in tab 
second is add  { link:true } to button definiition ( example in index.html )
that switch mousedown event to click event.
 
i have to see if click is good for all buttons

**Comment by takashi-tk** [comment]
It seems to work perfectly.
Thank you !
