### ISSUE TITLE
User want to have an option to set font color

### ISSUE THREAD

**Issue by nidin** [lo-th/uil#2]
**What?**
Component user want to have an option to set font color
for example Title font color

**Why?**
Right now all text content has white color.

**How?**
`ui.add('title', {name: 'Sun', id: "--", fontColor: "#D4B87B"});`

![image](https://cloud.githubusercontent.com/assets/198246/12786218/4c5f4b94-ca90-11e5-9268-940806bf0b8e.png)

**Comment by lo-th** [comment]
updated add new fontColor
maybe add titleColor for first text like' Renderer Option'

**Comment by lo-th** [comment]
yes now is 
titleColor: for title color
and 
fontColor: for other text and svg icon

**Comment by nidin** [comment]
Awesome :+1:
