### ISSUE TITLE
Graph.setValue needs to update internals

### ISSUE THREAD

**Issue by ndahn** [lo-th/uil#27]
Graph.setValue() is inherited, so it only updates Graph.value. But it also needs to update Graph.v and Graph.lng, otherwise the graphics won't be updated. Could be done the same way as in the constructor, i.e.

```
this.value = value;
this.lng = value.length;
for (var i = 0; i < this.lng; i++) {
    if (this.neg) _this.v[i] = (1 + value[i] / this.multiplicator) * 0.5;
    else this.v[i] = value[i] / this.multiplicator;
}
```

**Comment by lo-th** [comment]
Ok is fixed
