### ISSUE TITLE
Touch events not working

### ISSUE THREAD

**Issue by ndahn** [lo-th/uil#28]
I have this weird issue where most of the time UIL is not responding to touch events and I can't figure out why. On mobiles changing the screen orientation usually helps, on desktops resizing the window (sometimes). This happens in Firefox and Chrome, didn't try others. My UIL version is up to date.

**To reproduce:**
To test on desktop you can open one of the example pages (e.g. [UIL Test](http://lo-th.github.io/uil/examples/uil_test.html)), open the browser console (F12 in Firefox), switch to Responsive Design Mode (phone icon) and then make sure that touch events are enabled at the top (icon should be blue). 
It also consistently happens with the site I'm developing ([https://rocksi.net](https://rocksi.net)), both on desktop and mobile. UIL is in the robot view in the top right.

Any idea on how to solve this?

**Comment by lo-th** [comment]
should work now
