### ISSUE TITLE
Error when .listen() is used with 'Number' type inputs.

### ISSUE THREAD

**Issue by modulatedthreat** [lo-th/uil#29]
when .listen() is put on a numeric input I get console errors.

uil.js:5749 Uncaught TypeError: Cannot create property '0' on number '5'
    at Numeric.validate (uil.js:5749)
    at Object.keyup (uil.js:2020)
    at Object.handleEvent (uil.js:1649)

Uncaught TypeError: Cannot create property '0' on number '-0.63'
    at Numeric.validate (uil.js:5749)
    at Object.clearInput (uil.js:1950)
    at Gui.handleEvent (uil.js:7543)
    at Object.handleEvent (uil.js:1687)

going to line 376 in src/proto/Numeric.js we see: this.value[i] = nx; 
this.value is a number, not an array. To attempt an easy fix I changed it to: this.setValue(nx);
That stopped the errors, but the .listen() doesnt work, and the value does not update.
To recreate the problem just open the uil_listen.js example and change one of the inputs to type: 'Number'.

My ultimate goal is to have a slider and a numeric text input keep control and sync with a variable.

**Comment by lo-th** [comment]
Hi 
well this.value should be a  array 
problem's is on function setValue
thanks to see that 
is fixed

**Comment by modulatedthreat** [comment]
Thank you!!
uil.js is WAY better than dat.gui.
I dont know why it doesn't get more attention.

**Comment by modulatedthreat** [comment]
I have a question.
https://github.com/williammanco/uniforms-gui uses your code to put a slider with a text number input on the same line.
I cant figure out how they get your code to do that.
For example, the way the variable "uRed"  can be controlled in the sandbox https://codesandbox.io/s/4xn7po9l90 on the readme is exactly what I'm trying to do.
Is there something already built in that does this?

**Comment by lo-th** [comment]
Well you can use gui with a object  {}
material.uniform is a object with propriety like uRed 
so to update material you can use 
`ui.add( material.uniform, 'uRed ', { min:-5, max:5 } )`
no need use listen because the object is link to slider
so propriety uRed is update by gui

hope that help

**Comment by modulatedthreat** [comment]
Sorry, I wasn't very clear, and its not a big deal, but I was talking about the slider type and clicking on the number beside the slider and typing a different number in to change it.

**Comment by lo-th** [comment]
ha ok :)
is only possible in basic slider.
not include in knob or Circular
