### ISSUE TITLE
cannot add  a value when set the gui to canvas mode

### ISSUE THREAD

**Issue by Xposeder** [lo-th/uil#34]
when set the gui to canvas mode, can not add a new value。It will be no reactions and 
stuck. One solution to this is first dispose a value and then add a new one at the sametime.
![image](https://user-images.githubusercontent.com/72307252/164578242-1718509e-7242-4d7a-8a13-bb257f3d9317.png)
Just dispose a value in the canvas mode also works.

**Comment by lo-th** [comment]
hi not sure to understand the problem's 
can you make example

**Comment by Xposeder** [comment]
> hi not sure to understand the problem's can you make example

I tried to reproduce the problem on your example, but it worked fine, so I think the problem might be somewhere else, sorry to bother you, I'll close the question.
