### ISSUE TITLE
User want to have an options to set label width (AW) and value width (BW)

### ISSUE THREAD

**Issue by nidin** [lo-th/uil#4]
**What?**
Component user want to have an option to set label width (AW) and value width (BW)

**Why?**
Right now label width (AW) is size / 3
and value width (BW) is ((size / 3 * 2) - 10)

**How?**
case 1: new UIL.Gui({ size:300, labelWidth:200});
case 2: new UIL.Gui({ size:300, valueWidth:200});
case 3: new UIL.Gui({ labelWidth:200, valueWidth:200});
case 4: new UIL.Gui({ size:300, labelWidth:200, valueWidth:200}); //in this case; size should override

![image](https://cloud.githubusercontent.com/assets/198246/13205813/f54b0b62-d8f0-11e5-83e3-7d22b77c9e54.png)

**Comment by lo-th** [comment]
now you can set percent of title 
for all in new UIL.Gui( { Tpercent:30 } );
or for each module
ui.add('list',   { Tpercent:30, name:'list',  list:list2, height:40});
