### ISSUE TITLE
Expanding list inside a group is not pushing other groups down

### ISSUE THREAD

**Issue by nidin** [lo-th/uil#7]
Expanding list inside a group is not pushing other groups down

**Collapsed**
![image](https://cloud.githubusercontent.com/assets/198246/13206500/61b73038-d8ff-11e5-8b7e-1eb96fec25c1.png)

**Expanded**
![image](https://cloud.githubusercontent.com/assets/198246/13206501/65409a28-d8ff-11e5-98c4-c5f87ab11611.png)

**Comment by lo-th** [comment]
yep is ok now
